import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-GradBlue">
        <header><img src="/img/logo.png" alt="logo" className="h-40 w-auto inline-block align-middle" /></header>
        {children}
      </body>
    </html>
  );
}
